### ISSUE TITLE
ubuntu 18.04 install error 

### ISSUE THREAD

**Issue by shamjyothi** [SumoLogic/sumo-collector-puppet-module#45] opened 2020-04-30 11:21 UTC
The puppet module is run during server boot up which installs and configures the sumo module. 

The installation is done using the 'script based installer' using these options. 

```
  class { 'sumo':
    accessid                   => $sumo_access_id,
    accesskey                  => $sumo_access_key,
    use_package                => false,
    local_config_mgmt          => true,
    sync_sources_override      => true,
    sumo_json_sync_source_path => 'puppet:///modules/profile/sumo/usr/local/sumo/sumo.os.json'
  }
```
The puppet run fails 
```
[mNotice: /Stage[main]/Sumo::Nix_install/Exec[Execute sumo]/returns: executed successfully^[[0m
^[[1;31mError: Systemd start for collector failed!
journalctl log for collector:
-- Logs begin at Thu 2020-04-30 08:21:03 UTC, end at Thu 2020-04-30 09:14:52 UTC. --
Apr 30 09:14:52 ip-masked systemd[1]: Starting LSB: @app.long.name@...
Apr 30 09:14:52 ip-masked collector[2902]: Starting SumoLogic Collector...
Apr 30 09:14:52 ip-masked collector[2902]: SumoLogic Collector is already running.
Apr 30 09:14:52 ip-masked systemd[1]: collector.service: Control process exited, code=exited status=1
Apr 30 09:14:52 ip-masked systemd[1]: collector.service: Failed with result 'exit-code'.
Apr 30 09:14:52 ip-masked systemd[1]: Failed to start LSB: @app.long.name@.
^[[0m
^[[1;31mError: /Stage[main]/Sumo::Nix_install/Service[collector]/ensure: change from 'stopped' to 'running' failed: Systemd start for collector failed!
journalctl log for collector:
-- Logs begin at Thu 2020-04-30 08:21:03 UTC, end at Thu 2020-04-30 09:14:52 UTC. --
Apr 30 09:14:52 ip-masked systemd[1]: Starting LSB: @app.long.name@...
Apr 30 09:14:52 ip-masked collector[2902]: Starting SumoLogic Collector...
Apr 30 09:14:52 ip-masked collector[2902]: SumoLogic Collector is already running.
Apr 30 09:14:52 ip-masked systemd[1]: collector.service: Control process exited, code=exited status=1
Apr 30 09:14:52 ip-masked systemd[1]: collector.service: Failed with result 'exit-code'.
Apr 30 09:14:52 ip-masked systemd[1]: Failed to start LSB: @app.long.name@.
^[[0m
^[[mNotice: /Stage[main]/Sumo::Nix_install/Service[collector]: Triggered 'refresh' from 1 event^[[0m
^[[mNotice: /Stage[main]/Os_hardening::Sysctl/Sysctl[fs.suid_dumpable]/value: changed live value from '2' to '0'^[[0m
^[[mNotice: EC2 Role: haproxy^[[0m
```

however the sumo installation is complete. There are sumo PIDs active and the logs are getting ingested to the cloud ok. 

```
root@ip-masked:/opt/SumoCollector/logs# ps -eaf | grep -i sumo
root      2705     1  0 09:14 ?        00:00:00 /opt/SumoCollector/./wrapper /opt/SumoCollector/./config/wrapper.conf wrapper.syslog.ident=collector wrapper.pidfile=/opt/SumoCollector/./collector.pid wrapper.daemonize=TRUE wrapper.name=collector wrapper.displayname=SumoLogic Collector wrapper.statusfile=/opt/SumoCollector/./collector.status wrapper.java.statusfile=/opt/SumoCollector/./collector.java.status wrapper.lockfile=/var/lock/subsys/collector wrapper.script.version=3.5.33
root      2708  2705  3 09:14 ?        00:00:21 /opt/SumoCollector/jre/bin/java -XX:+UseParallelGC -server -Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx128m -Djava.library.path=./19.288-3/bin/native/lib -classpath ./19.288-3/lib/HikariCP-java7-2.4.13.jar:./19.288-3/lib/aether-api-0.9.0.M3.jar:./19.288-3/lib/aether-util-0.9.0.M3.jar:./19.288-3/lib/ant-1.8.4.jar:./19.288-3/lib/ant-launcher-1.8.4.jar:./19.288-3/lib/aopalliance-repackaged-2.4.0-b34.jar:./19.288-3/lib/archaius-core-0.7.6.SUMO-4.jar:./19.288-3/lib/archaius-scala_2.12-0.7.6.SUMO-4.jar:./19.288-3/lib/avro-1.8.2.jar:./19.288-3/lib/avro-ipc-1.8.2.jar:./19.288-3/lib/avrox-19.288-2.jar:./19.288-3/lib/aws-java-sdk-core-1.11.707.jar:./19.288-3/lib/aws-java-sdk-kms-1.11.707.jar:./19.288-3/lib/aws-java-sdk-s3-1.11.707.jar:./19.288-3/lib/backport-util-concurrent-3.1.jar:./19.288-3/lib/c3p0-0.9.5.5.jar:./19.288-3/lib/classgraph-4.8.43.jar:./19.288-3/lib/classworlds-1.1.jar:./19.288-3/lib/collector-19.288-3.jar:./19.288-3/lib/collector-base-19.288-1.jar:./19.288-3/lib/collector-interchange-19.288-1.jar:./19.288-3/lib/collector-native-19.288-1.jar:./19.288-3/lib/collector-util-19.288-1.jar:./19.288-3/lib/commons-cli-1.2.jar:./19.288-3/lib/commons-codec-1.12.jar:./19.288-3/lib/commons-collections-3.2.2.jar:./19.288-3/lib/commons-compress-1.19.jar:./19.288-3/lib/commons-configuration-1.10.jar:./19.288-3/lib/commons-httpclient-3.1.jar:./19.288-3/lib/commons-io-2.4.jar:./19.288-3/lib/commons-lang-2.6.jar:./19.288-3/lib/commons-logging-1.2.jar:./19.288-3/lib/compiler-0.9.6.jar:./19.288-3/lib/docker-java-3.0.17.jar:./19.288-3/lib/doxia-logging-api-1.1.jar:./19.288-3/lib/doxia-sink-api-1.1.jar:./19.288-3/lib/ecc-25519-java-1.0.3.jar:./19.288-3/lib/eddsa-0.2.0.jar:./19.288-3/lib/guava-19.0.jar:./19.288-3/lib/hk2-api-2.4.0-b34.jar:./19.288-3/lib/hk2-locator-2.4.0-b34.jar:./19.288-3/lib/hk2-utils-2.4.0-b34.jar:./19.288-3/lib/httpclient-4.5.10.jar:./19.288-3/lib/httpcore-4.4.12.jar:./19.288-3/lib/install4j-maven-plugin-1.0.7.jar:./19.288-3/lib/ion-java-1.0.2.jar:./19.288-3/lib/jackrabbit-jcr-commons-2.1.0.jar:./19.288-3/lib/jackrabbit-webdav-2.1.0.jar:./19.288-3/lib/jackson-annotations-2.
```

However on the m/c, the service configured on the OS called 'collector' has a status of 'Active: failed'. 

```
sj@ip-masked:~$ service collector status
● collector.service - LSB: @app.long.name@
   Loaded: loaded (/etc/init.d/collector; generated)
   Active: failed (Result: exit-code) since Thu 2020-04-30 09:14:52 UTC; 8min ago
     Docs: man:systemd-sysv-generator(8)
```

If I try to start the service 'collector', that fails as well. 

To fix the scenario, I have to manually kill the sumo PIDs and start the collector. 

```
root@ip-masked:/opt/SumoCollector/logs# kill -9 2705

root@ip-masked:/opt/SumoCollector/logs# service collector restart
root@ip-masked:/opt/SumoCollector/logs# service collector status
● collector.service - LSB: @app.long.name@
   Loaded: loaded (/etc/init.d/collector; generated)
   Active: active (running) since Thu 2020-04-30 09:42:21 UTC; 3s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 21292 ExecStart=/etc/init.d/collector start (code=exited, status=0/SUCCESS)
    Tasks: 46 (limit: 4417)
   CGroup: /system.slice/collector.service
           ├─21382 /opt/SumoCollector/./wrapper /opt/SumoCollector/./config/wrapper.conf wrapper.syslog.ident=collector wrapper.pidfile=/opt/SumoCollector/./collector.pid wrapper.daemonize=TRUE wrapper.name=collector
           └─21385 /opt/SumoCollector/jre/bin/java -XX:+UseParallelGC -server -Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx128m -Djava.library.path=./19.288-3/bin/native/lib -classpath ./19.288-3/lib/HikariCP-

Apr 30 09:42:18 ip-masked systemd[1]: Starting LSB: @app.long.name@...
Apr 30 09:42:18 ip-masked collector[21292]: Starting SumoLogic Collector...
Apr 30 09:42:18 ip-masked collector[21292]: Removed stale pid file: /opt/SumoCollector/./collector.pid
Apr 30 09:42:21 ip-masked collector[21292]: Waiting for SumoLogic Collector......
Apr 30 09:42:21 ip-masked collector[21292]: running: PID:21382
Apr 30 09:42:21 ip-masked systemd[1]: Started LSB: @app.long.name@.
```

Most likely the install command (https://github.com/SumoLogic/sumologic-collector-puppet-module/blob/098bb2864d67d7faa821d282b74d3f89d6517128/manifests/nix_install.pp#L389)  also kicks off the sumo processes before the service is configured.

**Comment by arunpatyal** [comment] 2020-04-30 12:03
@shamjyothi Can you please check the collector log under /opt/sumocollector/logs directory? Is there any error when the collector fails to start the first time? Also, is the collector already installed on this machine or is it a new installation? Finally, which release are you using?

**Comment by shamjyothi** [comment] 2020-04-30 12:11
This is a new installation using 0.2.4. This problem is also present in the earlier release as well.  
The collector.log is present in the /opt/SumoCollector/logs directory and it continuously updated. As the logs are processed and visible in sumo, there is no error with the sumo process. 

Its the service 'collector' that errors out. 

Here is the output from the puppet run
```
^[[mNotice: /Stage[main]/Sumo::Nix_install/Exec[Download Sumo Executable]/returns: executed successfully^[[0m
^[[mNotice: /Stage[main]/Sumo::Nix_install/Exec[Execute sumo]/returns: executed successfully^[[0m
^[[1;31mError: Systemd start for collector failed!
journalctl log for collector:
-- Logs begin at Thu 2020-04-30 11:32:16 UTC, end at Thu 2020-04-30 11:59:12 UTC. --
Apr 30 11:59:12 ip-masked systemd[1]: Starting LSB: @app.long.name@...
Apr 30 11:59:12 ip-masked collector[2905]: Starting SumoLogic Collector...
Apr 30 11:59:12 ip-masked collector[2905]: SumoLogic Collector is already running.
Apr 30 11:59:12 ip-masked systemd[1]: collector.service: Control process exited, code=exited status=1
Apr 30 11:59:12 ip-masked systemd[1]: collector.service: Failed with result 'exit-code'.
Apr 30 11:59:12 ip-masked systemd[1]: Failed to start LSB: @app.long.name@.
```

Could this be because there is no PID file specified in the collector.service file (referring to this https://github.com/SumoLogic/sumologic-collector-chef-cookbook/issues/141#issuecomment-455467673) ?

**Comment by arunpatyal** [comment] 2020-04-30 12:17
Ok. Thanks for the update. I will try to reproduce the issue.

**Comment by arunpatyal** [comment] 2020-05-01 14:20
I cannot reproduce the issue, here is the output of the puppet run:

 ```
ubuntu@ip-10-1-3-95:/opt$ sudo /opt/puppetlabs/bin/puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for ip-10-1-3-95
Info: Applying configuration version '1588342472'
Info: Computing checksum on file /usr/local/sumo/sumo64.sh
Info: /Stage[main]/Sumo::Nix_install/File[sumo_executable_rem]: Filebucketed /usr/local/sumo/sumo64.sh to puppet with sum 2f2c745a8a95064a719e26fad55e46d0
Notice: /Stage[main]/Sumo::Nix_install/File[sumo_executable_rem]/ensure: removed
Notice: /Stage[main]/Sumo::Nix_install/Exec[Download Sumo Executable]/returns: executed successfully
Notice: /Stage[main]/Sumo::Nix_install/Exec[Execute sumo]/returns: executed successfully
Info: /Stage[main]/Sumo::Nix_install/Exec[Execute sumo]: Scheduling refresh of Service[collector]
Notice: /Stage[main]/Sumo::Nix_install/Service[collector]: Triggered 'refresh' from 1 event
Notice: Applied catalog in 42.63 seconds`
```
Here is my config:

```node 'ip-10-1-3-95' { # Ubuntu 18.04
class { 'sumo':
  accessid       => '<access_id>',
  accesskey      => '<access_key',
  manage_sources => false,
  collector_url  => 'https://collectors.sumologic.com',
  sync_sources_override  => true,
  use_package    => false,
  local_config_mgmt => true,
  sumo_json_sync_source_path => 'puppet:///modules/sumo/sumo_sync_nix.json'
}
}
```

Agent OS: 

```ubuntu@ip-10-1-3-95:/opt$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic```

Do you have any difference in config from above?

**Comment by shamjyothi** [comment] 2020-05-01 16:17
we do not use a puppet agent. We run puppet locally on the m/c from rc.local on 1st boot of the server. 

I also list the OS, puppet version and a latest runlog which shows the error. 

```
root@ip-10-13-3-45:/etc/puppet# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
and puppet version is 
```
     Puppet: 5.4.0
     Facter: 3.10.0
```

The run logs are similar to what I pasted earlier. 
```
^[[mNotice: /Stage[main]/Sumo::Nix_config/File[/etc/sumo/sumoVarFile.txt]/ensure: defined content as '{md5}7bb37b5eaeeabdbf4d27606f4bb66339'^[[0m
^[[mNotice: Environment: shadow^[[0m
^[[mNotice: /Stage[main]/Main/Node[default]/Notify[Environment: shadow]/message: defined 'message' as 'Environment: shadow'^[[0m
^[[mNotice: /Stage[main]/Sumo::Nix_install/Exec[Download Sumo Executable]/returns: executed successfully^[[0m
^[[mNotice: /Stage[main]/Sumo::Nix_install/Exec[Execute sumo]/returns: executed successfully^[[0m
^[[1;31mError: Systemd start for collector failed!
journalctl log for collector:
-- Logs begin at Fri 2020-05-01 14:59:19 UTC, end at Fri 2020-05-01 15:16:19 UTC. --
May 01 15:16:19 ip-masked systemd[1]: Starting LSB: @app.long.name@...
May 01 15:16:19 ip-masked collector[2893]: Starting SumoLogic Collector...
May 01 15:16:19 ip-masked collector[2893]: SumoLogic Collector is already running.
May 01 15:16:19 ip-masked systemd[1]: collector.service: Control process exited, code=exited status=1
May 01 15:16:19 ip-masked systemd[1]: collector.service: Failed with result 'exit-code'.
May 01 15:16:19 ip-masked systemd[1]: Failed to start LSB: @app.long.name@.
^[[0m
^[[1;31mError: /Stage[main]/Sumo::Nix_install/Service[collector]/ensure: change from 'stopped' to 'running' failed: Systemd start for collector failed!
journalctl log for collector:
-- Logs begin at Fri 2020-05-01 14:59:19 UTC, end at Fri 2020-05-01 15:16:19 UTC. --
May 01 15:16:19 ip-masked systemd[1]: Starting LSB: @app.long.name@...
May 01 15:16:19 ip-masked collector[2893]: Starting SumoLogic Collector...
May 01 15:16:19 ip-masked collector[2893]: SumoLogic Collector is already running.
May 01 15:16:19 ip-masked systemd[1]: collector.service: Control process exited, code=exited status=1
May 01 15:16:19 ip-masked systemd[1]: collector.service: Failed with result 'exit-code'.
May 01 15:16:19 ip-masked systemd[1]: Failed to start LSB: @app.long.name@.
^[[0m
^[[mNotice: /Stage[main]/Sumo::Nix_install/Service[collector]: Triggered 'refresh' from 1 event^[[0m
^[[mNotice: /Stage[last]/Motd/File[/etc/motd]: Dependency Service[collector] has failures: true^[[0m
^[[1;33mWarning: /Stage[last]/Motd/File[/etc/motd]: Skipping because of failed dependencies^[[0m
^[[mNotice: /Stage[last]/Motd/File[/etc/issue.net]: Dependency Service[collector] has failures: true^[[0m
^[[1;33mWarning: /Stage[last]/Motd/File[/etc/issue.net]: Skipping because of failed dependencies^[[0m
^[[mNotice: Applied catalog in 62.99 seconds
``` 
I don't see this error when puppet is run after system boot up is complete using the command 
```
root@ip-masked:/etc/puppet# puppet apply ./manifests/ --show_diff
2020-05-01 15:38:21 +0000
Warning: ModuleLoader: module 'sumo' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules\n   (file & line not available)
Warning: The function 'hiera' is deprecated in favor of using 'lookup'. See https://docs.puppet.com/puppet/5.4/reference/deprecated_language.html\n   (file & line not available)
Notice: Compiled catalog for ip-masked.ec2.internal in environment shadow in 1.57 seconds
Notice: /Stage[main]/Sumo::Nix_install/File[sumo_executable_rem]/ensure: removed
Notice: Environment: shadow
Notice: /Stage[main]/Main/Node[default]/Notify[Environment: shadow]/message: defined 'message' as 'Environment: shadow'
Notice: /Stage[main]/Sumo::Nix_install/Exec[Download Sumo Executable]/returns: executed successfully
Notice: /Stage[main]/Sumo::Nix_install/Exec[Execute sumo]/returns: executed successfully
Notice: /Stage[main]/Sumo::Nix_install/Service[collector]: Triggered 'refresh' from 1 event
Notice: /Stage[last]/Motd/File[/etc/motd]/content:
--- /etc/motd	2020-05-01 15:03:26.559470152 +0000
+++ /tmp/puppet-file20200501-19036-s3o8e6	2020-05-01 15:39:04.644091901 +0000
@@ -6,10 +6,10 @@
 relevant  authorities for further  action.  By continuing past
 this point, you expressly consent to this monitoring.

-   Last Run: 2020-05-01 15:02:47 +0000
+   Last Run: 2020-05-01 15:38:21 +0000
 Environment:
-       FQDN: ip-masked.ec2.internal
-         IP: ip-masked.ec2.internal
+       FQDN: ip-masked.ec2.internal
+         IP: ip-masked.ec2.internal
      Puppet: 5.4.0
      Facter: 3.10.0


Notice: /Stage[last]/Motd/File[/etc/motd]/content: content changed '{md5}f3f7103bd238c14c19d09416b293b7ba' to '{md5}89bf616b49454b8f4c72f5b01cfa0b56'
Notice: Applied catalog in 36.50 seconds
```

**Comment by arunpatyal** [comment] 2020-05-04 10:04
@shamjyothi I was able to reproduce the issue. It indeed looks like a similar issue to the chef issue: https://github.com/SumoLogic/sumologic-collector-chef-cookbook/issues/141#issuecomment-455467673. As it looks like a core collector issue and not Puppet issue, please follow up in the original support case. Please do mention the chef issue.

**Comment by arunpatyal** [comment] 2020-05-10 09:50
@shamjyothi Closing this for now, please open a new issue if required.

**Closed as completed** 2020-05-10 09:50 UTC
